# Generated by Django 3.0.6 on 2020-05-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='superheroe',
            options={'ordering': ('nombre',)},
        ),
    ]
