# Generated by Django 3.0.6 on 2020-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_auto_20200528_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
                ('publicationyear', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='fecha',
            field=models.CharField(default=0.0005, max_length=30),
        ),
    ]
