# Generated by Django 3.0.6 on 2020-05-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0004_auto_20200528_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
